# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-18 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('heading', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('marked', models.BooleanField(default=False)),
                ('obj_type', models.IntegerField(choices=[(0, 'Non editable'), (1, 'Editable')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('heading', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('marked', models.BooleanField(default=False)),
                ('obj_type', models.IntegerField(choices=[(0, 'Non editable'), (1, 'Editable')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('topic_title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reading',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Section'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Section'),
        ),
    ]
